on:
  push:
    branches: [main]

concurrency:
  group: ${{ github.worklow }}-${{ github.ref }}
  cancel-in-progress: true

name: Render and Publish

permissions: 
    contents: write
    pages: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@c1b50d36cf3c22b3dc7e530bd1b36634e824e545 # v2
        with:
          # To install LaTeX to build PDF book 
          tinytex: true 
          # uncomment below and fill to pin a version
          # version: SPECIFIC-QUARTO-VERSION-HERE
      
      - name: Setup R
        uses: r-lib/actions/setup-r@b7e68d63e51bdf225997973e2add36d551f60f02 # v2

      - name: Install dependencies
        uses: r-lib/actions/setup-renv@b7e68d63e51bdf225997973e2add36d551f60f02 # v2
        with:
          cache-version: 1

      - name: Publish to GitHub Pages (and render) 
        uses: quarto-dev/quarto-actions/publish@c1b50d36cf3c22b3dc7e530bd1b36634e824e545 # v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # this secret is always available for github actions
      
